import { QuestDifficulty } from '../types';

export interface QuestTemplate {
  title: string;
  description?: string;
  difficulty: QuestDifficulty;
  tags?: string[];
}

// A collection of example quest templates that our "AI" can choose from.
// In a real application this list could be generated by an AI model or
// fetched from a remote service. Here we provide a curated set of
// productivity-oriented tasks with varying difficulty.
const questTemplates: QuestTemplate[] = [
  {
    title: 'Morning meditation',
    description: 'Spend 10 minutes meditating to start your day with clarity.',
    difficulty: 'easy',
    tags: ['mindfulness', 'health']
  },
  {
    title: 'Read a chapter of a book',
    description: 'Pick up a book you’ve been meaning to read and finish one chapter.',
    difficulty: 'easy',
    tags: ['learning', 'reading']
  },
  {
    title: 'Write a journal entry',
    description: 'Reflect on your day and write down your thoughts in a journal.',
    difficulty: 'easy',
    tags: ['mindfulness', 'writing']
  },
  {
    title: 'Complete a 30‑minute workout',
    description: 'Do a full body workout or go for a brisk walk/run.',
    difficulty: 'normal',
    tags: ['fitness', 'health']
  },
  {
    title: 'Learn a new coding concept',
    description: 'Spend at least 45 minutes learning or practicing a coding concept you are not familiar with.',
    difficulty: 'hard',
    tags: ['learning', 'coding']
  },
  {
    title: 'Tidy up your workspace',
    description: 'Declutter and organise your desk to improve productivity.',
    difficulty: 'easy',
    tags: ['organisation', 'health']
  },
  {
    title: 'Plan your week',
    description: 'Take 30 minutes to plan your tasks and priorities for the upcoming week.',
    difficulty: 'normal',
    tags: ['planning', 'productivity']
  },
  {
    title: 'Cook a healthy meal',
    description: 'Choose a nutritious recipe and prepare it from scratch.',
    difficulty: 'normal',
    tags: ['health', 'cooking']
  },
  {
    title: 'Take a digital detox',
    description: 'Spend at least 2 hours away from screens and social media.',
    difficulty: 'hard',
    tags: ['wellness', 'mindfulness']
  }
];

/**
 * Selects a random quest template from the predefined list. Each call
 * yields a potentially different suggestion. This mimics an AI
 * recommendation system by providing variety and surprise.
 */
export function getRandomQuestTemplate(): QuestTemplate {
  const index = Math.floor(Math.random() * questTemplates.length);
  return questTemplates[index];
}